package com.thyng.domain.thing;

import java.util.Map;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.thyng.persistence.AbstractEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
@DynamoDBTable(tableName = Thing.TABLE_NAME)
public class Thing extends AbstractEntity {
	private static final long serialVersionUID = -2269905804622007163L;

	public static final String TABLE_NAME = "thing";

	@DynamoDBRangeKey 
	@DynamoDBAutoGeneratedKey 
	private String id;
	
	@DynamoDBHashKey 
	private String tenantId;
	
	@NotBlank private String name;
	@NotNull private ThingStatus status;
	@NotNull private Long inactivityPeriod;
	private Map<@NotBlank String, @NotBlank String> attributes;
	
}
