package com.thyng.domain.thing;

import java.util.Map;

import javax.validation.constraints.Min;
import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTypeConvertedEnum;
import com.thyng.persistence.AbstractEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
@DynamoDBTable(tableName = Thing.TABLE_NAME)
public class Thing extends AbstractEntity {
	private static final long serialVersionUID = -2269905804622007163L;
	public static final String TABLE_NAME = "thing";

	@DynamoDBRangeKey 
	@DynamoDBAutoGeneratedKey 
	private String id;
	
	@DynamoDBHashKey 
	@NotBlank private String tenantId;
	
	
	@NotNull @Min(60) private Long inactivityPeriod;
	@NotBlank @Size(min = 3, max = 255) private String name;
	private Map<@NotBlank String, @NotBlank String> attributes;
	@NotNull @DynamoDBTypeConvertedEnum private ThingStatus status;
	
}
