package com.thyng.util;

public interface Constant {

	String COUNTER = "counters";
	String TENANT = "tenants";
	String GATEWAY = "gateways";
	String TEMPALTE = "templates";
	String SENSOR = "sensors";
	String ACTUATOR = "actuators";
	String ATTRIBUTE = "attributes";
	String THING = "things";
	String THING_INFO = "thing-infos";
	String THING_GROUP = "thing-groups";
	String THING_GROUP_MAPPING = "thing-group-mappings";
	String TRIGGER = "triggers";
	String TRIGGER_INFO = "trigger-infos";
	String ACTION = "actions";
	String USER = "users";
	String USER_GROUP = "user-groups";
	String USER_GROUP_MAPPING = "user-group-mappings";
	String METRIC = "metrics";
	
	String TENANT_CREATED = "TENANT_CREATED";
	String TENANT_UPDATED = "TENANT_UPDATED";
	String TENANT_DELETED = "TENANT_DELETED";
	String GATEWAY_CREATED = "GATEWAY_CREATED";
	String GATEWAY_UPDATED = "GATEWAY_UPDATED";
	String GATEWAY_DELETED = "GATEWAY_DELETED";
	String TEMPLATE_CREATED = "TEMPLATE_CREATED";
	String TEMPLATE_UPDATED = "TEMPLATE_UPDATED";
	String TEMPLATE_DELETED = "TEMPLATE_DELETED";
	String THING_CREATED = "THING_CREATED";
	String THING_UPDATED = "THING_UPDATED";
	String THING_DELETED = "THING_DELETED";
	String THING_GROUP_CREATED = "THING_GROUP_CREATED";
	String THING_GROUP_UPDATED = "THING_GROUP_UPDATED";
	String THING_GROUP_DELETED = "THING_GROUP_DELETED";
	String THING_GROUP_MAPPING_CREATED = "THING_GROUP_MAPPING_CREATED";
	String THING_GROUP_MAPPING_UPDATED = "THING_GROUP_MAPPING_UPDATED";
	String THING_GROUP_MAPPING_DELETED = "THING_GROUP_MAPPING_DELETED";
	String TRIGGER_CREATED  = "TRIGGER_CREATED";
	String TRIGGER_UPDATED = "TRIGGER_UPDATED";
	String TRIGGER_DELETED = "TRIGGER_DELETED";
	String TRIGGER_INFO_CREATED  = "TRIGGER_INFO_CREATED";
	String TRIGGER_INFO_UPDATED = "TRIGGER_INFO_UPDATED";
	String TRIGGER_INFO_DELETED = "TRIGGER_INFO_DELETED";
	String ACTION_CREATED = "ACTION_CREATED";
	String ACTION_UPDATED = "ACTION_UPDATED";
	String ACTION_DELETED = "ACTION_DELETED";
	String USER_CREATED = "USER_CREATED";
	String USER_UPDATED = "USER_UPDATED";
	String USER_DELETED = "USER_DELETED";
	String USER_GROUP_CREATED = "USER_GROUP_CREATED";
	String USER_GROUP_UPDATED = "USER_GROUP_UPDATED";
	String USER_GROUP_DELETED = "USER_GROUP_DELETED";
	String USER_GROUP_MAPPING_CREATED = "USER_GROUP_MAPPING_CREATED";
	String USER_GROUP_MAPPING_UPDATED = "USER_GROUP_MAPPING_UPDATED";
	String USER_GROUP_MAPPING_DELETED = "USER_GROUP_MAPPING_DELETED";
	
	int ORDER_MODULE_CORE = Integer.MAX_VALUE;
	int ORDER_MODULE_DYNAMO = 0;
	int ORDER_MODULE_TIMESTREAM = 0;
	int ORDER_MODULE_CACHE_MAP = 1;
	
}
