package com.thyng.domain.tenant;

import java.io.Serializable;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.NotNull;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.thyng.domain.Identifiable;
import com.thyng.domain.Nameable;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@DynamoDBTable(tableName = Tenant.TABLE_NAME)
@EqualsAndHashCode(callSuper = false, of={"id", "name"})
public class Tenant implements Identifiable<String>, Nameable, Serializable {
	private static final long serialVersionUID = -4444782720017595800L;

	public static final String TABLE_NAME = "tenant";

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey
	private String id;
	
	@NotBlank private String name;
	@NotNull private Boolean enabled = Boolean.TRUE;
	
}
