package com.thyng.domain.sensor;

import javax.validation.constraints.NotBlank;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.thyng.persistence.AbstractEntity;

import lombok.Data;
import lombok.EqualsAndHashCode;

@Data
@EqualsAndHashCode(callSuper = true)
@DynamoDBTable(tableName = Sensor.TABLE_NAME)
public class Sensor extends AbstractEntity {
	private static final long serialVersionUID = 5122567002461543932L;

	public static final String TABLE_NAME = "sensor";

	@DynamoDBRangeKey 
	@DynamoDBAutoGeneratedKey 
	private String id;
	
	@DynamoDBHashKey 
	private String tenantId;
	
	@NotBlank private String name;
	@NotBlank private String unit;
	@NotBlank private String thingId;
}
